"""update primary key sim tag user

Revision ID: 1f8edbe165ba
Revises: 340497f73ee7
Create Date: 2020-10-28 23:40:39.991269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8edbe165ba'
down_revision = '340497f73ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
