"""replace url_id by sim_number atribute to sim_tag_user

Revision ID: 2c02f6744c08
Revises: ae13e1bc1cfe
Create Date: 2020-10-28 11:28:48.007949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c02f6744c08'
down_revision = 'ae13e1bc1cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sim_tag_user', sa.Column('sim_number', sa.Integer(), nullable=False))
    op.drop_column('sim_tag_user', 'url_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sim_tag_user', sa.Column('url_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('sim_tag_user', 'sim_number')
    # ### end Alembic commands ###
