"""update sim tag user key

Revision ID: 340497f73ee7
Revises: a4f1956a64fe
Create Date: 2020-10-28 23:33:54.830639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340497f73ee7'
down_revision = 'a4f1956a64fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sim_tag_user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sim_tag_user', type_='unique')
    # ### end Alembic commands ###
