"""add tag table

Revision ID: 360e2554a8cb
Revises: 7b5e4701ffce
Create Date: 2020-11-05 23:17:07.739705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360e2554a8cb'
down_revision = '7b5e4701ffce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
