"""add tag table

Revision ID: 4b4d68b44484
Revises: 360e2554a8cb
Create Date: 2020-11-05 23:18:30.121444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4d68b44484'
down_revision = '360e2554a8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
