"""add tag table

Revision ID: 7b5e4701ffce
Revises: d59b259380b4
Create Date: 2020-11-05 23:12:04.338100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5e4701ffce'
down_revision = 'd59b259380b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
