"""delete sim tag user table

Revision ID: 808b81ce67e5
Revises: 1f8edbe165ba
Create Date: 2020-10-28 23:48:50.237500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '808b81ce67e5'
down_revision = '1f8edbe165ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='sim_tag_user')
    op.drop_table('sim_tag_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_tag_user',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag_date', mysql.DATETIME(), nullable=True),
    sa.Column('start', mysql.DATETIME(), nullable=True),
    sa.Column('finish', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('sim_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'tag_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'sim_tag_user', ['id'], unique=True)
    # ### end Alembic commands ###
