"""add tag table

Revision ID: 92ee6b9d901b
Revises: 4b4d68b44484
Create Date: 2020-11-06 13:38:28.488132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ee6b9d901b'
down_revision = '4b4d68b44484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
