"""init table

Revision ID: 998f8137e787
Revises: 
Create Date: 2020-10-28 00:01:13.837406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998f8137e787'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country',
    sa.Column('postal_code', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('postal_code')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_owner', sa.String(length=45), nullable=True),
    sa.Column('time', sa.String(length=45), nullable=True),
    sa.Column('otp', sa.String(length=45), nullable=True),
    sa.Column('raw_message', sa.String(length=200), nullable=True),
    sa.Column('from_number', sa.String(length=45), nullable=True),
    sa.Column('date', sa.String(length=45), nullable=True),
    sa.Column('shop_id', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop',
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('postal_code', sa.String(length=45), nullable=True),
    sa.Column('channel_id', sa.String(length=45), nullable=True),
    sa.Column('correspond_apicall', sa.String(length=200), nullable=True),
    sa.Column('shop_master_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_sim',
    sa.Column('shop_id', sa.String(length=45), nullable=False),
    sa.Column('sim_number', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('shop_id', 'sim_number')
    )
    op.create_table('sim',
    sa.Column('sim_number', sa.String(length=45), nullable=False),
    sa.Column('tty_gateway', sa.String(length=45), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('expire_date', sa.String(length=45), nullable=True),
    sa.Column('balance', sa.Float(precision=45), nullable=True),
    sa.Column('check', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('sim_number')
    )
    op.create_table('sim_url',
    sa.Column('sim_number', sa.String(length=45), nullable=False),
    sa.Column('url', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('sim_number', 'url')
    )
    op.create_table('url',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=45), nullable=True),
    sa.Column('first_name', sa.String(length=45), nullable=True),
    sa.Column('last_name', sa.String(length=45), nullable=True),
    sa.Column('role', sa.String(length=45), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('url')
    op.drop_table('sim_url')
    op.drop_table('sim')
    op.drop_table('shop_sim')
    op.drop_table('shop')
    op.drop_table('message')
    op.drop_table('country')
    op.drop_table('channel')
    # ### end Alembic commands ###
