"""adding description atrubute to sim tag user table

Revision ID: a4f1956a64fe
Revises: 2c02f6744c08
Create Date: 2020-10-28 22:43:33.914666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f1956a64fe'
down_revision = '2c02f6744c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sim_tag_user', sa.Column('description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sim_tag_user', 'description')
    # ### end Alembic commands ###
