"""add status atribute to sim_tag_user

Revision ID: ae13e1bc1cfe
Revises: b0a22dd84675
Create Date: 2020-10-28 11:14:57.223053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae13e1bc1cfe'
down_revision = 'b0a22dd84675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sim_tag_user', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sim_tag_user', 'status')
    # ### end Alembic commands ###
